server:
  port: 8080
logging:
  level:
    root: INFO


spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: dev

mybatis-plus:

  # 配置扫描xml
  mapper-locations:
    - classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fengzijk.springdemo.entity
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    local-cache-scope: statement
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
